const API='http://localhost:5000/api';
const skills=[['JAVA','Java',88],['HTML','HTML5',92],['CSS','CSS3',88],['JS','JavaScript',82],['RE','React.js',72],['NO','Node.js',78],['EX','Express.js',76],['SQL','MySQL',84],['MG','MongoDB',76],['GH','Git & GitHub',82],['DS','Data Structures & Algorithms',75]];
document.getElementById('skillsGrid').innerHTML=skills.map(([i,n,l])=>`<article class="skill"><div class="skill-icon">${i}</div><h3>${n}</h3><div class="bar"><i style="--level:${l}%"></i></div></article>`).join('');
const fallback=[{name:'ArtGallery Website',description:'Online platform for showcasing and purchasing artwork with seller uploads, pricing, cart, buying, payment page and authentication.',technologies:['HTML','CSS','JavaScript','Node.js','Express.js','MongoDB','Mongoose','EJS'],github:'#',liveDemo:'#'}];
function renderProjects(items){document.getElementById('projectsGrid').innerHTML=items.map(p=>`<article class="project"><div class="project-cover"></div><div class="project-body"><h3>${p.name}</h3><p>${p.description}</p><div class="tags">${(p.technologies||[]).map(t=>`<span>${t}</span>`).join('')}</div><div class="project-links"><a href="${p.github||'#'}" target="_blank">GitHub ↗</a><a href="${p.liveDemo||'#'}" target="_blank">Live Demo ↗</a></div></div></article>`).join('')}
fetch(`${API}/projects`).then(r=>r.ok?r.json():Promise.reject()).then(renderProjects).catch(()=>renderProjects(fallback));
const root=document.documentElement;document.getElementById('themeToggle').onclick=()=>{const light=root.dataset.theme==='light';root.dataset.theme=light?'dark':'light';localStorage.theme=root.dataset.theme};if(localStorage.theme)root.dataset.theme=localStorage.theme;
document.querySelector('.menu').onclick=()=>document.querySelector('.nav-links').classList.toggle('open');document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=()=>document.querySelector('.nav-links').classList.remove('open'));document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('contactForm').onsubmit=async e=>{e.preventDefault();const s=document.getElementById('formStatus');s.textContent='Sending...';try{const data=Object.fromEntries(new FormData(e.target));const r=await fetch(`${API}/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();s.textContent='Message sent successfully.';e.target.reset()}catch{s.textContent='Backend unavailable. Start the server to submit messages.'}};
